import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} max-h-screen antialiased flex flex-col h-screen mx-auto`}
      >
        <Header />

        <main className="flex-1 min-h-0 container mx-auto space-y-5">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
